# Configuration for deterministic rules and model defaults
# Switched to OpenAI-compatible endpoint (LM Studio).

model:
  provider: openai_compat
  model_name: openai/gpt-oss-20b
  # The app reads OPENAI_BASE_URL and OPENAI_API_KEY from environment.
  # Defaults below are safe for LM Studio; override via env if needed.
  base_url: http://192.168.1.226:1234/v1
  max_new_tokens: 768 
  temperature: 0.0

rules:
  failed_login_window_min: 60
  failed_per_user: 8
  failed_per_ip: 20
  impossible_travel_window: 90
